### PR TITLE
Blowing up PRs with epic refactoring

### PR DESCRIPTION
**Pull request by skull-squadron**
Consolidated refactoring and improvements:
- Messages no longer get lost.
- No crash during first test.
- No junk/temporary file triggering.
- Desktop notifications using `terminal-notifier`, including compilation errors.
- Workaround rebar termio/tty corruption.
- Recompiles code correctly between runs.

Anti-features:
- Getting rid of shell (currently).
- Getting real erlang's argc/argv for original `rebar3` invocation (doesn't appear possible without a NIF).

### CODE REVIEW

**Comment by NobbZ** [comment]
I do trust in you and your skills. I'm missing the necessary environment and time to do even basic manual testing. I will merge it for now, so one who uses it from git does benefit directly.

Hex-users will have to wait though. I wont be able to release before mid of may.

**Comment by NobbZ** [comment]
PS: In general I do strongly prefer small isolated PRs for easier reviewing.

**Comment by NobbZ** [comment]
And please do me a favor, walk over the open issues that may be fixed by this and comment there referencing this PR, so I'll know where to close. Will take a day or two though...

**Comment by skull-squadron** [comment]
@NobbZ  #2 and #5 can be closed also.

**Review by Blade272008 — APPROVED** [review]
Great job

**Pull request merged**
